resources:
- ../../base
patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: angular
commonLabels:
  app: dev-angular
namespace: dev
configMapGenerator:
- behavior: merge
  literals:
  - ENV=dev
  name: angular
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: angular-k8s
  newName: 5h4k4r/angular-k8s
  newTag: 18d523d05d896902cdda2ca18a5cbccabe758bcd
