resources:
  - ../../base
patchesJson6902:
  - path: ingress-patch.yaml
    target:
      group: extensions
      kind: Ingress
      name: angular
      version: v1
commonLabels:
  app: dev-angular
namespace: dev
configMapGenerator:
  - behavior: merge
    literals:
      - ENV=dev
    name: angular
