name: Publish Docker image

on:
  push:
    branches:
      - dev
    paths-ignore:
      - "*.md"
      - ".vscode/**"
concurrency:
  group: deploy-dev
  cancel-in-progress: true

jobs:
  deploy:
    uses: 5h4k4r/angular-app/.github/workflows/deploy-base.yaml@dev
    with:
      image: $GITHUB_SHA
      environment: dev
