name: Deploy

on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
      env_name:
        type: string
        required: true

    secrets:
      KUBECONFIG:
        required: true

env:
  NAMESPACE: dev

jobs:
  deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3

      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "4.4.1"

      - name: Edit kustomization file
        working-directory: kubernetes/overlays/dev
        run: kustomize edit set image IMAGE="${{ inputs.image }}"

      - name: Deploy
        working-directory: kubernetes/overlays/${{ inputs.env_name }}
        run: |-

          kustomize build | kubectl apply -f -
          kubectl rollout -n "$NAMESPACE" status deployment/angular -w --timeout=3m
